import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import HydrationStore from "./providers/HydrationStore";
import QueryProvider from "./providers/QueryProvider";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Weather",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${dmSans.className} antialiased`}
        suppressHydrationWarning
      >
        <QueryProvider>
          <HydrationStore>{children}</HydrationStore>
        </QueryProvider>
      </body>
    </html>
  );
}
